# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='time',
        ),
    ]
